#a workflow to generate a commit a javadoc site for a project

name: generate javadoc

on:
    #when a commit is pushed to main
    push:
        branches:
            - main

jobs:
    format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Generate Javadoc
              run: ./gradlew javadoc
            - name: Commit Javadoc
              env:
                #this is the token that was created earlier
                GITHUB_TOKEN: ${{ secrets.TOKEN }}
              run: |
                # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
                git config --global user.name "GitHub Actions"
                git config --global user.email "actions@github.com"
                git add -f lib/build/docs/javadoc
                git commit -m "Javadoc for ${{ github.sha }}"
                git push
            #commit the javadoc folder, the folder has been added to the .gitignore file